---
language: node_js
node_js: '8'
services:
  - postgresql
script:
  - npm run build
  - npm run test
  - nohup npm run start & 
  - sleep 3
  - npm run test
cache:
  directories: 
    - node_modules
install: 
  - npm install 
  - npm run build
before_script:
  - psql -U postgres -c 'create database myapp_test;' 
env: 
  - PORT=3000
dist: trusty