---
language: node_js
node_js: '8'
services:
  - postgresql
script:
  - npm run build
  - npm run test
  - nohup npm run start & 
  - sleep 3
  - npm run test
cache:
  directories: 
    - node_modules
install: 
  - npm install 
  - npm run build
before_script:
  - psql -U postgres -c 'create database myapp_test;' 
  - psql -c "CREATE USER lets WITH PASSWORD 'wait';" -U postgres
env: 
  - PORT=3000 DATABASE_URL=postgres://lets:wait/myapp_test NODE_ENV=test
dist: trusty